version: '3.5'
services:
  api1: &api
    image: krymancer/rinha-de-backend-2024-q1-dotnet
    hostname: api1
    depends_on:
      - db
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '100MB'
  api2:
    <<: *api
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./conf/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '300MB'
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx/:/etc/nginx/
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'
networks:
  default:
    driver: bridge
    name: network